### ISSUE TITLE
conda package entry point

### ISSUE THREAD

**Issue by kbrindley** [conda-forge/ccx2paraview-feedstock#3]
You can create a Conda package executable that installs on PATH if you add an entry point: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#python-entry-points. Then users don't need to find the source file to run the project.

recipe.yaml
```
build:
  entry_points:
    - ccx2paraview = ccx2paraview.ccx2paraview:main
```

**Comment by jan-janssen** [comment]
Sounds good - can you open a pull request?

**Comment by kbrindley** [comment]
I can open a PR next week.

**Comment by kbrindley** [comment]
closed in https://github.com/conda-forge/ccx2paraview-feedstock/pull/5. closing.
