### ISSUE TITLE
missing vtk and numpy runtime dependencies

### ISSUE THREAD

**Issue by kbrindley** [conda-forge/ccx2paraview-feedstock#4]
The upstream package depends on vtk and numpy, but the package recipe does not list these in the ``build: run`` section.

https://github.com/calculix/ccx2paraview/blob/master/pyproject.toml#L8-L10

https://github.com/conda-forge/ccx2paraview-feedstock/blob/main/recipe/meta.yaml#L22-L23

**Comment by kbrindley** [comment]
VTK package from conda-forge is not compatible with Paraview package from conda-forge

```
$ conda search "vtk-base=9.3.1=qt_py312hc73667e_209" -c conda-forge --info | grep paraview -B 2
constraints : 
  - libboost_headers
  - paraview ==9999999999
```

Purpose of package is to make Paraview compatible files. Seems like it would be preferable to open those files from the same Conda environment. From my testing, the version of VTK installed as part of the conda-forge Paraview package will work for ccx2paraview. As a start, I think I would prefer to make Paraview the dependency instead of VTK, but...

This may not be desirable for all conda-forge users. Paraview may be a relatively heavy package compared to VTK? Hard to tell because both dependency lists are quite long and both include qt6, a usual reason for wanting a "lighter-weight" package dependency list.

It might be worth talking with the upstream project owner @imirzov to ask if they have a preference for how the conda-forge package handles the incompatible VTK/Paraview packages in the ccx2paraview dependencies. Maybe add numpy dependency and let user decide how to get VTK? Maybe build separate VTK and Paraview variant packages for conda-forge?

Seems like the reason the upstream doesn't have to worry about this is because there is no paraview package in PyPI. I guess if you have a stand-alone Paraview installation, it doesn't interfere with the pip installed packages or virtualenv.

```
$ pip install --dry-run paraview
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement paraview (from versions: none)
ERROR: No matching distribution found for paraview
```

https://pypi.org/search/?q=paraview

https://discourse.paraview.org/t/install-any-python-package-for-the-paraview-binary-release-using-pip/14437

**Comment by kbrindley** [comment]
@jan-janssen do you use this package with conda-forge installed VTK or Paraview? Do you have a preference for the runtime dependency?

**Comment by jan-janssen** [comment]
@kbrindley I do not have a strong opinion, I tried to use `ccx2paraview` but in the end the project moved in a different direction. So if we can make it more useful for you by modifying the recipe I am open to it.

**Comment by kbrindley** [comment]
@jan-janssen I can help maintain: https://github.com/conda-forge/ccx2paraview-feedstock/pull/7

My interest is in writing a fully open-source FEA workflow tutorial as an alternate to Abaqus: https://lanl-aea.github.io/waves/. I don't need a strict answer to paraview/vtk dependence for that. I can open a PR with the numpy dependence, but I'll leave the paraview/vtk up to the user until/unless this package receives more attention on conda-forge.

For my own curiosity, did you change data extraction tools, switch solvers, or something else?

**Comment by kbrindley** [comment]
closed with numpy fix in https://github.com/conda-forge/ccx2paraview-feedstock/pull/8. Issue https://github.com/conda-forge/ccx2paraview-feedstock/issues/9 addresses vtk/paraview
